// <auto-generated />
using BusinessTrackerAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessTrackerAPI.Migrations
{
    [DbContext(typeof(BusinessTrackerAPIContext))]
    [Migration("20210404012037_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BusinessTrackerAPI.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BusinessAge")
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BusinessSeating")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BusinessType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
